kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ss
  namespace: test
spec:
  strategy:
    type: Docker
    dockerStrategy: {}
  source:
    type: Dockerfile
    dockerfile: |-
      FROM registry.redhat.io/rhscl/httpd-24-rhel7

      # The run script uses standard ways to run the application
      CMD run-httpd
