apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-example
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: httpd-example
    server: https://kubernetes.default.svc
  source:
    path: httpd-example
    repoURL: https://github.com/olivierbegon/rosa.git
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Need to add the section below otherwise argo cd complains that the system is out of sync even when not.
  # ArgoCD uses the image hash as a reference and does not seem to see that the corresponding tag version/name is the same
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
